apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-student-iot
  namespace: education
  labels:
    app: edge-service-student-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service-student-iot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: edge-service-student-iot
    spec:
      tolerations:
        - key: "edge"
          operator: "Equal"
          value: "true"
          effect: "NoExecute"
      hostNetwork: true
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: edge-service-student-iot
          image: core.harbor.cz.shenlan.com/dbp-edu/edge-service-student-iot:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: env_profile
              valueFrom:
                configMapKeyRef:
                  name: edge-conf
                  key: env
            - name: edge_name
              valueFrom:
                configMapKeyRef:
                  name: edge-conf
                  key: edgeName
            - name: node_name
              valueFrom:
                configMapKeyRef:
                  name: edge-conf
                  key: nodeName
            - name: JAVA_OPTS
              value: '-Xms1024m -Xmx1024m -Duser.timezone=GMT+08'
            - name: log_dir
              value: /var/log/edu
            - name: opentracing.jaeger.enabled
              value: 'false'
            - name: bff_student_iot_url
              valueFrom:
                configMapKeyRef:
                  name: edge-conf
                  key: bffStudentIotUrl
            - name: edge_service_media_url
              valueFrom:
                configMapKeyRef:
                  name: edge-conf
                  key: edgeServiceMediaUrl
            - name: edge_service_biz_url
              valueFrom:
                configMapKeyRef:
                  name: edge-conf
                  key: edgeServiceBizUrl
          ports:
            - name: tcp-essential
              containerPort: 9001
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - wget
                - http://localhost:9001/actuator/health
                - -O
                - health
          volumeMounts:
            - mountPath: /var/log/edu
              name: persistent-log-storage
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
      volumes:
        - name: persistent-log-storage
          hostPath:
            type: DirectoryOrCreate
            path: /data/log/edu
