version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus:/prometheus
    # command:
    #   - 'config.file=/etc/prometheus/prometheus.yml'
    networks:
      - edu-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2g
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.1.2
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - edu-network
    restart: always

  grafana:
    image: grafana/grafana:7.5.4
    container_name: grafana
    hostname: grafana
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - /data/grafana:/var/lib/grafana
    networks:
      - edu-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g
  weave-scope:
    image: weaveworks/scope:1.13.2
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
    restart: always
networks:
  edu-network:
    external:
      name: edu-network