global:
  # How frequently to scrape targets by default. default = 1m
  scrape_interval: 5s
  # How long until a scrape request times out. default = 10s 
  scrape_timeout: 3s
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager)
  # external_labels:
  #   monitor: 'my-monitor'
scrape_configs:
  # The job name assigned to scraped metrics by default.
  - job_name: 'prometheus'
    # List of labeled statically configured targets for this job.
    static_configs:
      # The targets specified by the static config.
      - targets:
          - 'localhost:9090'

  - job_name: 'server'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'node-exporter:9100'
        labels:
          instance: server