server:
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 10000
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  main:
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8


# 管理端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# 应用自定义配置
sys:
  # 开启http请求log打印
  http-log:
    enable: true

# swagger通用配置
swagger:
  enabled: true
  global-parameters:
    - name: X-Accept-Locale
      description: Language
      default-value: zh_CN
      param-type: header
      data-type: String
      required: false

# 日志 相关
logging:
  file:
    path: ${log_dir:/var/log/edu}/${spring.application.name}
  level:
    root: info
  config: classpath:logback-spring.xml

logstash:
  host: 10.16.32.201
  port: 5044