version: "3"
services: 
  jenkins: 
    container_name: jenkins
    image: jenkins/jenkins
    privileged: true
    user: root
    ports: 
      - 18080:8080
      - 50000:50000
    volumes: 
      - ./jenkins_home:/var/jenkins_home
      - ~/.ssh:/var/jenkins_home/.ssh
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker 
      - /usr/bin/git:/usr/bin/git 