#spring:
#  cloud:
#    #    服务注册
#    consul:
#      host: consul.com
#      port: 8500
#      discovery:
#        heartbeat:
#          enabled: true
#        health-check-path: /health
#        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#        serviceName: ${spring.application.name}
#  rabbitmq:
#    #采用消息确认模式
#    publisher-confirms: true
#    publisher-returns: true