apiVersion: v1
kind: Deployment
metadata:
  name: mysql-edge-#EDGENAME#
  labels:
    name: mysql-edge
    type: edge
    edge: #EDGENAME#
  namespace: education
spec:
  replicas: 1
  selector:
    name: mysql-edge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql-edge
        edge: #EDGENAME#
    spec:
      nodeName: "#NODENAME#" #选择需要部署的边缘节点
      hostNetwork: true
      containers:
        - name: mysql-edge
          image: 'mysql:8.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Pa55WOrD"
          volumeMounts:                        #挂载容器中的目录到pvc nfs中的目录
            - name: psd
              mountPath: /var/lib/mysql
      volumes:
        - name: psd
          hostPath:
            type: DirectoryOrCreate
            path: /data/mysql