apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
    