apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-mysql
  namespace: edu-edge
  labels:
    app: edge-mysql
    namespace: edu-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: edge-mysql
    spec:
      hostNetwork: true
      containers:
        - name: edge-mysql
          image: 'mysql:5.7'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:                        #挂载容器中的目录到pvc nfs中的目录
            - name: psd
              mountPath: /var/lib/mysql
      volumes:
        - name: psd
          hostPath:
            type: DirectoryOrCreate
            path: /data/mysql