apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-conf
  namespace: edu-cloud-dev
data:
  ENV: "dev"
  NACOS_SERVER_ADDR: "nacos-headless.nacos.svc.cluster.local:8848"
  KEYCLOAK_URL: "https://edu-auth-internel.deepblueai.com/auth"
  # KEYCLOAK_URL: "http://10.16.32.151:31091/auth"
  KEYCLOAK_REALM: "dev"
  FILE_PREVIEW_URL: "http://10.16.32.187:30009"
  # FILE_PREVIEW_URL: "https://uat-edu-file-preview.deepblueai.com"