spring:
  redis:
    cluster:
      nodes:
        - 10.16.32.192:6380
        - 10.16.32.190:6380
        - 10.16.32.187:6380
        - 10.16.32.192:6381
        - 10.16.32.190:6381
        - 10.16.32.187:6381
    database: 0
    password: DeepblueEdu222
    maxAttempts: 5
    timeout: 3000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        maxActive: 8
        #连接池中的最大空闲连接
        maxIdle: 8
        #连接池中的最小空闲连接
        minIdle: 4
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: 3000