FROM apache/skywalking-java-agent:8.5.0-jdk8

MAINTAINER gsh
WORKDIR /opt/app

ADD target/service-user.jar app.jar
RUN touch app.jar

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar" ]
EXPOSE 7003
