swagger:
  api:
    title: 深兰AI数字教育平台API文档
    description: 云端存储服务
    version: '3.3'
    contact:
      name: guanshenghui
      url: http://${swagger.host}/business/v2/api-docs
      email: developer@deepblueai.com


spring:
  #  上传文件限制500MB
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

storage:
  engine: ${storage_engine:aws-s3} # 如果使用浪潮则设置为 aws-s3  如果使用ftp则设置为 ftp
  ftp:
    host: ${ftp_host:10.16.32.184}
    port: ${ftp_port:60021}
    username: ${ftp_account:deepblueftp}
    password: ${ftp_credential:deepblue}
    rootdir: ${ftp_rootdir:/data/ftp/files}
    connectTimeoutMillis: ${ftp_connect_timeout_millis:5000}
    baseUrl: ${ftp_base_url:http://10.16.32.184:8989}
  aws-s3:
    basebucket: ${aws_basebucket:edu-uat}
    bucket-range: '0-1000'
    access_key: ${aws_access_key:9HW9I7SJBRUPAMSD83K3}
    secret_key: ${aws_secret_key:WcQNDnpd2jbYCsiCsAs7ZixKPRhJo5PXXq9AbkyH}
    endpoint: ${aws_endpoint:10.16.138.26}
    baseUrl: ${aws_base_url:https://uat-edu-oss.deepblueai.com}


