version: '3.8'
services:
  skywalking-oap-server:
    container_name: skywalking-oap-server
    image: apache/skywalking-oap-server:8.5.0-es6
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      JAVA_OPTS: "-Xms512m -Xmx512m"
  skywalking-ui:
    container_name: skywalking-ui
    image: apache/skywalking-ui:8.5.0
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server
    restart: always
    ports:
      - 3380:8080
    environment:
      # 注意  本地部署配置host
      SW_OAP_ADDRESS: skywalking-oap-server-address:12800