version: '3'
services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    volumes:
      #      - /Users/gsh/Desktop/docker_volume/nexus_home/data:/nexus-data
      - ./data:/nexus-data
      # command:
      #      两个写入操作 只是为了解决启动后警告 可以去掉
      # /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
      # && echo never > /sys/kernel/mm/transparent_hugepage/enabled
      # && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 8081:8081
