apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: education-infra
  labels:
    app: keycloak
    release: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      release: infra
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: keycloak
        release: infra
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:11.0.1
          ports:
            - name: tcp-essential
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_SCHEMA
              value: public
            - name: DB_PASSWORD
              value: p@sade348
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: Pa55w0rd
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled"


---
apiVersion: v1            #必须
kind: Service             #必须
metadata:                 #必须
  name: keycloak
  namespace: education-infra
  labels:
    service: keycloak
spec:                   #必须
  selector:            #必须
    app: keycloak
    release: infra      #必须
  type: NodePort        #必须
  ports:
    - name: tcp-essential
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31091