version: '2'
services:
  nacos-server:
    container_name: nacos-server
    image: nacos/nacos-server:1.4.2
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.112.88
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&&useSSL=false
    volumes:
      - ./logs/:/home/nacos/logs
      - ./init.d/:/home/nacos/init.d
    ports:
      - 8848:8848
    # network_mode: host

