apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-migrations
          image: kong:2.1
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do kong migrations list; if [[ 0 -eq $? ]]; then exit 0; fi; sleep 2;  done;"
          env:
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_HOST
            - name: KONG_PG_USER
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_USER
            - name: KONG_PG_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_PASSWORD
      containers:
        - name: proxy
          env:
            - name: KONG_NGINX_WORKER_PROCESSES
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_NGINX_WORKER_PROCESSES
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_HOST
            - name: KONG_PG_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_PASSWORD