apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:0.14.9
          env:
            - name: DB_ADAPTER
              value: postgres
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONG_PG_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONGA_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONGA_PG_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kong-conf
                  key: KONGA_PG_PASSWORD
          ports:
            - name: konga
              containerPort: 1337
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: kong
spec:
  type: NodePort
  selector:
    app: konga
  ports:
    - name: konga
      port: 1337
      targetPort: 1337
      nodePort: 31337
      protocol: TCP
