apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: education
  labels:
    app: mysql
    type: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      type: cloud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mysql
        type: cloud
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-essential
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Pa66w0rd"
          volumeMounts:                        #挂载容器中的目录到pvc nfs中的目录
            - name: psd
              mountPath: /var/lib/mysql
      volumes:
        - name: psd
          hostPath:
            type: DirectoryOrCreate
            path: /data/mysql

---
apiVersion: v1            #必须
kind: Service             #必须
metadata:                 #必须
  name: mysql
  namespace: education  #必须
  labels:
    service: mysql
    type: cloud
spec:                   #必须
  selector:            #必须
    app: mysql
    type: cloud     #必须
  type: NodePort        #必须
  ports:
    - name: tcp-essential
      protocol: TCP
      port: 3306
      targetPort: 3306