apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-edge-node3
  labels:
    name: mysql-edge-node3
  namespace: education
spec:
  replicas: 1
  selector:
    name: mysql-edge-node3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql-edge-node3
    spec:
      nodeName: "edge.node3" #选择需要部署的边缘节点
      hostNetwork: true
      containers:
        - name: mysql-edge-node3
          image: 'mysql:8.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:                        #挂载容器中的目录到pvc nfs中的目录
            - name: psd
              mountPath: /var/lib/mysql
      volumes:
        - name: psd
          hostPath:
            type: DirectoryOrCreate
            path: /data/mysql