version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=gsh
            - MONGO_INITDB_ROOT_PASSWORD=gsh
        volumes:
            - /data/mongo/db:/data/db
            - /data/mongo/log:/var/log/mongodb
        ports:
            - 27017:27017