#spring:
#  profiles:
#    active:
#      - dev
#---
#spring:
#  profiles: dev
#  application:
#    name: config-server-dev
#---
#spring:
#  profiles: test
#  application:
#    name: config-server-test

spring:
  application:
    name: config-client
  cloud:
    #    服务注册
    consul:
      host: consul.com
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        health-check-path: /health
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
        serviceName: ${spring.application.name}
    #  开启消息跟踪
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
    #rabbitmq配置
  rabbitmq:
    #采用消息确认模式
    publisher-confirms: true
    publisher-returns: true
    password: guest
    username: guest
    host: 127.0.0.1
    port: 5672
      #监听配置
    listener:
      simple:
          #签收模式  manual手工签收 auto自动签收
        acknowledge-mode: manual
          #并发数
        concurrency: 5
          #最大并发数
        max-concurrency: 15
          #限流 一次最多几个消息被消费完之后消息才可被消费
        prefetch: 5
  #springboot2.0 更新部分
  #是否需要权限拉去，默认是true,如果不false就不允许你去拉取配置中心Server更新的内容
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
#    配置中心配置
#
