# 所有deployment 指定节点，必须满足:  edge=gezhi
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-algorithm-dispatch
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-biz
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-file-manager
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-media
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-student-iot
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-teacher-iot
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-video-process
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - shangyin
