apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-student-iot
  namespace: edu-cloud
  labels:
    app: bff-student-iot
    type: cloud
    k8s.kuboard.cn/layer: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-student-iot
      type: cloud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bff-student-iot
        type: cloud
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - cloud
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: bff-student-iot
          image: core.harbor.cz.shenlan.com/dbp-edu/bff-student-iot:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: nacos_server_addr
              valueFrom:
                configMapKeyRef:
                  name: cloud-conf
                  key: NACOS_SERVER_ADDR
            - name: env_profile
              valueFrom:
                configMapKeyRef:
                  name: cloud-conf
                  key: ENV
            - name: JAVA_OPTS
              value: '-Xms1536m -Xmx1536m -Duser.timezone=GMT+08'
            - name: log_dir
              value: /var/log/edu
            - name: opentracing.jaeger.enabled
              value: 'false'
          resources:
            limits:
              cpu: 500m
              memory: 2G
          ports:
            - name: tcp-essential
              containerPort: 7101
              protocol: TCP
          readinessProbe:
            httpGet:
              port: tcp-essential
              path: /actuator/health
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
---
apiVersion: v1            #必须
kind: Service             #必须
metadata:                 #必须
  name: bff-student-iot
  namespace: edu-cloud       #必须
  labels:
    app: bff-student-iot
    type: cloud
spec:                   #必须
  selector:            #必须
    app: bff-student-iot
    type: cloud
  type: NodePort        #必须
  ports:
    - name: tcp-essential
      protocol: TCP
      port: 7101
      targetPort: 7101
      nodePort: 30011