apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-exam
  namespace: edu-cloud
  labels:
    app: service-exam
    type: cloud
    k8s.kuboard.cn/layer: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-exam
      type: cloud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: service-exam
        type: cloud
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - cloud
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: service-exam
          image: core.harbor.cz.shenlan.com/dbp-edu/service-exam:latest
          imagePullPolicy: Always
          env:
            - name: nacos_server_addr
              valueFrom:
                configMapKeyRef:
                  name: cloud-conf
                  key: NACOS_SERVER_ADDR
            - name: env_profile
              valueFrom:
                configMapKeyRef:
                  name: cloud-conf
                  key: ENV
            - name: JAVA_OPTS
              value: '-Xms1024m -Xmx1024m -Duser.timezone=GMT+08'
            - name: log_dir
              value: /var/log/edu
            - name: opentracing.jaeger.enabled
              value: 'false'
          resources:
            limits:
              cpu: 500m
              memory: 2G
          ports:
            - name: tcp-essential
              containerPort: 7003
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health
              port: tcp-essential
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: tcp-essential
              path: /actuator/health
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              port: tcp-essential
              path: /actuator/health
            initialDelaySeconds: 30
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
          volumeMounts:
            - mountPath: /var/log/edu
              name: persistent-log-storage
      volumes:
        - name: persistent-log-storage
          hostPath:
            type: DirectoryOrCreate
            path: /data/log/edu
---
apiVersion: v1            #必须
kind: Service             #必须
metadata:                 #必须
  name: service-exam
  namespace: edu-cloud        #必须
  labels:
    app: service-exam
    type: cloud
spec:                   #必须
  selector:            #必须
    app: service-exam
    type: cloud      #必须
  type: ClusterIP     #必须
  ports:
    - name: tcp-essential
      protocol: TCP
      port: 7003
      targetPort: 7003