spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.16.32.223:3306/edu_foundation?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: edu
    password: p#vfJKW1rU
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000

swagger:
  api:
    title: 深兰AI数字教育平台API文档
    description: 基础信息管理服务
    version: '0.1'
    contact:
      name: guanshenghui
      url: http://${swagger.host}/business/v2/api-docs
      email: developer@deepblueai.com

mapper:
  mappers:
    - com.gsh.springcloud.starter.mysql.tk.CommonMapper
    - tk.mybatis.mapper.common.special.InsertListMapper
    - tk.mybatis.mapper.common.IdsMapper
  identity: MYSQL
  not-empty: false
  enable-method-annotation: true
  before: false
  enum-as-simple-type: true
  wrap-keyword: '`{0}`'
  check-example-entity-class: true
  use-simple-type: false
mybatis:
  type-aliases-package: com.gsh.springcloud.foundation.domain.model
  mapper-locations:
    - classpath*:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: false
  helper-dialect: ${mapper.identity}
  support-methods-arguments: true