server:
  port: 8001
spring:
  application:
    name: py-sidecar


sidecar:
  port: 3000
  health-uri: http://localhost:${sidecar.port}/health


#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000
#ribbon.ConnectTimeout=5000
#ribbon.ReadTimeout=5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
