server:
  port: 8091

spring:
  #应用服务名
  application:
    name: service-config-server

  cloud:
#    服务注册
    consul:
      host: consul.com
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        health-check-path: /health
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
        serviceName: ${spring.application.name}
#    注册中心
    config:
      server:
        git:
          #配置文件所在目录
          search-paths: /**
          #配置文件仓库地址
          uri: https://github.com/gsh978079141/configServerFiles.git
          #配置仓库的分支
          default-label: master
          #用户名与密码
          username:
          password:
    #  开启消息跟踪
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
  #rabbitmq配置
  rabbitmq:
    password: guest
    username: guest
    host: rabbit.com
    port: 5672
    #监听配置
    listener:
      simple:
        #签收模式  manual手工签收 auto自动签收
        acknowledge-mode: manual
        #并发数
        concurrency: 5
        #最大并发数
        max-concurrency: 15
        #限流 一次最多几个消息被消费完之后消息才可被消费
        prefetch: 5
#springboot2.0 更新部分
#是否需要权限拉去，默认是true,如果不false就不允许你去拉取配置中心Server更新的内容
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
