FROM grafana/grafana:7.2.0

#WORKDIR /var/lib/grafana/plugins
#
#COPY grafana-piechart-panel WORKDIR/grafana-piechart-panel

#
#RUN chmod 777 /var/lib/grafana
#
#chown 472:472 grafana_data -R

#chown 472:472 /data/grafana -R

ADD grafana-piechart-panel /var/lib/grafana/plugins/grafana-piechart-panel