{
 "title": "edu dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "学生班级分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n$__unixEpochTo() AS time,\ntmp.ct as value ,cs.`name` as metric\nfrom (\nSELECT count(s.id) as ct,s.class_id from student s where s.is_deleted=0 group by s.class_id \n) as tmp inner join classes as cs on tmp.class_id=cs.id and cs.is_deleted=0"
    }
   ]
  },
  {
   "title": "考试试卷统计",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select count(1) as value,STR_TO_DATE(tmp.exam_date ,'%Y-%m-%d') as time_sec\nfrom \n(SELECT ex.id ,em.exam_date from examinee ex left join exam em on ex.exam_id=em.id where ex.deleted=0 and em.deleted=0\n) as tmp\nGROUP BY STR_TO_DATE(tmp.exam_date,'%Y-%m-%d')"
    }
   ]
  },
  {
   "title": "学生总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) AS value,\n  '学生' as misc\nFROM student as a \nWHERE a.is_deleted=0"
    }
   ]
  },
  {
   "title": "教师总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n$__unixEpochTo() AS time,\n  count(1) AS value\nFROM teacher as a \nWHERE\n    a.is_deleted=0\n"
    }
   ]
  },
  {
   "title": "日志",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:166",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:164", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}