version: '3'

services:
  # 流媒体服务
  edge-service-media:
    image: core.harbor.cz.shenlan.com/dbp-edu/edge-service-media:latest
    restart: always
    environment:
      - env_profile=dev
      - log_dir=/var/log/edu
      - JAVA_OPTS=-Xms2048m -Xmx2048m -Duser.timezone=GMT+08 -Dkms.url=ws://192.168.41.69:8888/kurento
    ports:
      - 7006:7006
    volumes:
      - /root/log/edu:/var/log/edu
    networks:
      - edu-network
  # 算法服务网关
  edge-server-algorithm-gateway:
    image: core.harbor.cz.shenlan.com/dbp-edu/edge-server-algorithm-gateway:latest
    restart: always
    environment:
      - env_profile=dev
      - log_dir=/var/log/edu
      - JAVA_OPTS=-Xms2048m -Xmx2048m -Duser.timezone=GMT+08
    ports:
      - 9100:9100
    volumes:
      - /root/log/edu:/var/log/edu
    networks:
      - edu-network
  # 算法调度服务
  edge-service-algorithm-dispatch:
    image: core.harbor.cz.shenlan.com/dbp-edu/edge-service-algorithm-dispatch:latest
    restart: always
    environment:
      - env_profile=dev
      - log_dir=/var/log/edu
      - JAVA_OPTS=-Xms2048m -Xmx2048m -Duser.timezone=GMT+08
    ports:
      - 9101:9101
    volumes:
      - /root/log/edu:/var/log/edu
    networks:
      - edu-network
networks:
  edu-network:
    external: true