apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-edge-#EDGENAME#
  namespace: education
  labels:
    app: rabbit-edge
    type: edge
    edge: #EDGENAME#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-edge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbit-edge
        edge: #EDGENAME#
    spec:
      nodeName: "#NODENAME#" #选择需要部署的边缘节点
      hostNetwork: true
      containers:
        - image: bitnami/rabbitmq:latest
          imagePullPolicy: IfNotPresent
          name: rabbit-edge
          ports:
            - containerPort: 15672
              name: rabbit15672
              protocol: TCP
            - containerPort: 5672
              name: rabbit5672
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: psd
              mountPath: /bitnami
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: psd
          hostPath:
            type: DirectoryOrCreate
            path: /data/rabbitmq
