---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
  annotations:
    # Cloud-provider specific annotations
    # GKE
    # GKE creates a L4 LB for any service of type LoadBalancer
    # TODO figure out how to enable Proxy Protocol on an L4 LB for GKE
    # AWS
    # Use NLB over ELB
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # Use L4 LB so that Kong can do TLS termination
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    # Enable Proxy Protocol when Kong is listening for proxy-protocol
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  type: NodePort
  selector:
    app: ingress-kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
      protocol: TCP
      nodePort: 30443


---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
spec:
  selector:
    app: ingress-kong
  ports:
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: admin-ssl
      port: 8444
      targetPort: 8444
      protocol: TCP