apiVersion: v1
kind: PersistentVolume
metadata:
  name: lostash-pv-node4
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lostash-storage
  local:
    path: /opt/lostash-volume/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lostash-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer